In [ ]:
G=6.67*pow(10,-13)
m=6*pow(10,24)
M=7.34*pow(10,22)
r=3.84*pow(10,8)
f1=(G*M*m)
f2 = (r**2)
f3=f1/f2
print(" ",f3)


  1.9920979817708332e+18


In [ ]:
dict1={"key1":"john","key2":"medhat","key3":"mohamed"}
print(dict1.values())
print(dict1.keys())


dict_values(['john', 'medhat', 'mohamed'])
dict_keys(['key1', 'key2', 'key3'])


In [ ]:
lst1=["fady","mohamed","medhat","john"]
for index in range(4):
 print(" ",lst1[index])

  fady
  mohamed
  medhat
  john


In [ ]:
num1=input("please enter the first value:\n")
num2=input("please the second value:\n")
num3=int(num1)+int(num2)
print("the result is",num3 )




please enter the first value:
2
please the second value:
412
the result is 414


In [ ]:
def Simplecalc(num1,num2,operator):
  if operator == '/':
   num3=float(num1) / float(num2)
   return num3
  elif operator == '+':
    num3=float(num1) + float(num2)
    return num3
  elif operator == '**' :
    num3=float(num1) ** float(num2)
    return num3
  elif operator == '-' :
    num3=float(num1) - float(num2)
    return num3
  elif operator == '//' :
    num3=float(num1) // float(num2)
    return num3
  elif operator == '%' :
    num3=float(num1) % float(num2)
    return num3
  else:
    return 0;


print('enter the first number:\n')
num1=input()
print('enter the second number:\n')
num2=input()
print("enter the operator:\n")
operator:str=input()
Simplecalc(num1,num2,operator)


enter the first number:

5
enter the second number:

2
enter the operator:

//


2.0

In [ ]:
class computer :
  Computer_Model : str ='unknown'
  def __init__(self,cpu,ram,gpu,year) :
    self.cpu=cpu
    self.gpu=gpu
    self.ram=ram
    self.year=year
  @classmethod  
  def model(cls) :
    cls.Computer_Model="Appel"
    return cls.Computer_Model

com1=computer('i3',8,'gtx 950',2016)
com2=computer('i5',16,'gtx 1080',2018)
com3=computer('core2duo',6,'gt 610',2015)
com4=computer('i7',16,'rtx 3090',2022)
com5=computer('i7',32,'rtx 1080ti',2019)
com6=computer('i7',32,'gtx1080',2021)
print(f"all computer models are {computer.model()} brand")
print("")



class tools(computer) :
  def __init__(self,cpu,gpu,ram,year,monitor,keyboard,mouse):
    super(). __init__(cpu,gpu,ram,year)
    self.monitor=monitor
    self.mouse=mouse
    self.keyboard=keyboard
  def Tool_Type(self):
    print(f"the pc criteria is {self.cpu} cpu and {self.gpu} gpu and {self.ram} GB ram")
    print(f"the year of production is {self.year}")
    print(f"the tools types are {self.keyboard} and {self.mouse}")
    print(f"the monitor type is {self.monitor} ")
    print('**********************************************************')

   

tools1=tools('i3',8,'gtx 950',2016,'monitor1','mouse1','keyboard1')
tools2=tools('i5',16,'gtx 1080',2018,'monitor2','mouse2','keyboard2')    
tools3=tools('core2duo',6,'gt 610',2015,'monitor3','mouse3','keyboard3')    
tools4=tools('i7',16,'rtx 3090',2022,'monitor4','mouse4','keyboard4')    
tools5=tools('i7',32,'rtx 1080ti',2019,'monitor5','mouse5','keyboard5')    
tools6=tools('i7',32,'gtx1080',2021,'monitor6','mouse6','keyboard6')    

tools1.Tool_Type()
tools2.Tool_Type()
tools3.Tool_Type()
tools4.Tool_Type()
tools5.Tool_Type()
tools6.Tool_Type()



all computer models are Appel brand

the pc criteria is i3 cpu and gtx 950 gpu and 8 GB ram
the year of production is 2016
the tools types are mouse1 and keyboard1
the monitor type is monitor1 
**********************************************************
the pc criteria is i5 cpu and gtx 1080 gpu and 16 GB ram
the year of production is 2018
the tools types are mouse2 and keyboard2
the monitor type is monitor2 
**********************************************************
the pc criteria is core2duo cpu and gt 610 gpu and 6 GB ram
the year of production is 2015
the tools types are mouse3 and keyboard3
the monitor type is monitor3 
**********************************************************
the pc criteria is i7 cpu and rtx 3090 gpu and 16 GB ram
the year of production is 2022
the tools types are mouse4 and keyboard4
the monitor type is monitor4 
**********************************************************
the pc criteria is i7 cpu and rtx 1080ti gpu and 32 GB ram
the year of production is 2019


In [ ]:
# initializing lists
name = ["Fady", "John", "Matthew", "David"]
roll_no = [4, 1, 3, 2]
marks = [40, 50, 60, 70]
 
# using zip() to map values
mapped = zip(name, roll_no, marks)
 
arranged = set(mapped)
 
print(arranged)
print("\n")
 
# unzipping values
namz, roll_noz, marksz = zip(*arranged)
 

print(namz)
print(roll_noz)
print(marksz)

{('Fady', 4, 40), ('John', 1, 50), ('David', 2, 70), ('Matthew', 3, 60)}


('Fady', 'John', 'David', 'Matthew')
(4, 1, 2, 3)
(40, 50, 70, 60)


In [ ]:
def multip1(arr1,arr2):
 arr3=[] 
 return [arr1_i*arr2_i for arr1_i,arr2_i in zip(arr1,arr2)]


arr1=[1,3,2,2]
arr2=[4,1,5,2]
arr3=multip1([1,3,2,2],[4,1,5,2])
print(arr3)




[4, 3, 10, 4]


In [ ]:
def scalar(v1,num):
 x=[]  
 for i in v1:
   x.append(int(i)*int(num))
 return x  

num=input("please enter a value\n")
print(scalar([1,2,4,6,3],num))    


please enter a value
2
[2, 4, 8, 12, 6]


In [ ]:
def shape(x):   
 num_rows=len(x)   # number of rows
 num_columns=len(x[0]) #number of elements in each row=num of col per row
 return num_rows,num_columns

x=[[1,2,2,3],
   [1,5,2,4],
   [5,4,3,7]]

print(shape(x))  





(3, 4)


In [ ]:
def matrix_multip2(a,b):
  c=[]
  for i in range(len(a)):
    for j in range(len(a[i])): 
      # for each element (j) in ith row in matrix a : add a[i][j]+b[i][j] :
     c.append(a[i][j]*b[i][j])
  return c

a=[[0,3,5],
   [4,3,2],
   [1,7,2]]

b=[[1,1,3],
   [2,1,3],
   [5,3,7]]

print(matrix_multip2(a,b))    

[0, 3, 15, 8, 3, 6, 5, 21, 14]


In [ ]:
def matrix_add(a,b):
  c=[]
  for i in range(len(b)):
    for j in range(len(b[i])):
      c.append(a[i][j]+b[i][j])
  return c

a=[[1,4,5],
   [1,3,2],
   [2,6,2]]

b=[[6,3,2],
   [1,2,4],
   [7,4,2]]

print(matrix_add(a,b))

[7, 7, 7, 2, 5, 6, 9, 10, 4]


In [ ]:
def matrix_multisc(a,b):
  c=[]
  for i in range(len(a)):
    for j in range(len(a[i])): 
      # for each element (j) in ith row in matrix a : add a[i][j]+b[i][j] :
     c.append(a[i][j] * b)
  return c

a=[[0,3,5],
   [4,3,2]]

b=.5

print(matrix_multisc(a,b))    

[0.0, 1.5, 2.5, 2.0, 1.5, 1.0]


In [ ]:
def matrix_sub(a,b):
  c=[]
  for i in range(len(b)):
    for j in range(len(b[i])):
      c.append(a[i][j]-b[i][j])
  return c

a=[[1,4,5],
   [1,3,2],
   [2,6,2]]

b=[[6,3,2],
   [1,2,4],
   [7,4,2]]

print(matrix_sub(a,b))

[-5, 1, 3, 0, 1, -2, -5, 2, 0]


In [ ]:
#operations on matrices

def matrix_add(v1,v2):
  v3=[]
  for i in range(len(v1)):
    for j in range(len(v1[i])):
      v3.append(v1[i][j]+v2[i][j])
  return v3

def matrix_sub(v1,v2):
  v3=[]
  for i in range(len(v1)):
    for j in range(len(v1[i])):
      v3.append(v1[i][j]-v2[i][j])
  return v3

def matrix_scalar_multip(v1,c):
  v3=[]
  for i in range(len(v1)):
    for j in range(len(v1[i])):
      v3.append(v1[i][j]*c)
  return v3

def matrix_vector_multip(v1,v3):
  v4=[]
  for i in range(len(v1)):
    for j in range(len(v1[i])):
      v4.append(v1[i][j]*v3[i])
  return v4

def matrix_multip(v1,v2):
  v3=[]
  for i in range(len(v1)):
    for j in range(len(v1[i])):
      v3.append(v1[i][j]*v2[i][j])
  return v3

v1=[[1,4,2],[8,2,1],[7,4,2]]
v2=[[4,2,1],[6,3,2],[1,2,5]]
c=2
v3=[3,2,1]

print("matrix addition: ",matrix_add(v1,v2))
print("matrix subtraction: ",matrix_sub(v1,v2))
print("matrix vector multiplication: ",matrix_vector_multip(v1,v3))
print("matrix scalar multiplication: ",matrix_scalar_multip(v1,c))
print("matrix multiplication: ",matrix_multip(v1,v2))

matrix addition:  [5, 6, 3, 14, 5, 3, 8, 6, 7]
matrix subtraction:  [-3, 2, 1, 2, -1, -1, 6, 2, -3]
matrix vector multiplication:  [3, 12, 6, 16, 4, 2, 7, 4, 2]
matrix scalar multiplication:  [2, 8, 4, 16, 4, 2, 14, 8, 4]
matrix multiplication:  [4, 8, 2, 48, 6, 2, 7, 8, 10]


In [ ]:
from numpy import ones
from numpy import empty
from numpy import array
from numpy import zeros
import numpy as np
v5=[[1,4,5],[2,1,4]]
a=empty([3,2])
arr1=array([[1,2,3],[5,3,5]])
a1=ones([2,3])
a2=zeros([2,1])

print(a1)
print('\n',arr1.shape)
print('\n',arr1.dtype)
print('\n',a)
print('\n',arr1)

arr2=np.empty([2,2])
arr2=np.zeros([2,1])
arr2=np.array([[2,1,3],[5,2,1]])

print(a2)
print('\n',a2.shape)
print('\n',a2.dtype)
print('\n',arr2)


a3=np.array([2,5,3])
a4=np.array([7,0,1])
a5=np.array([9,3,5])
a6=np.vstack((a3,a4,a5))
print(a6[1,1])

print(a6[1][2])
print(a6[:,:1])
split=2
train=a6[split:,:]
test=a6[:split,:]
print('\n',train)
print('\n',test)
print('\n\n\n')
input_train,output_train,input_test,output_test=train_test_split(data,80)
data=np.array([['a',23,1],['b',24,1],['c',25,0],['d',26,0],['e',27,1],['f',28,0],
               ['g',29,1],['h',20,1],['i',30,0],['j',33,1]])
def train_test_split(data,train_percent):
  midpoint=train_percent*len(data)/100
  train,test=data[:int(midpoint),:],data[int(midpoint):,:]
  X_train,Y_train=train[:,:-1],train[:,-1]
  X_test,Y_test=test[:,:-1],test[:,-1]
  return X_train,Y_train,X_test,Y_test

print(input_train)
print(output_train)
print(input_test)
print(output_test)

[[1. 1. 1.]
 [1. 1. 1.]]

 (2, 3)

 int64

 [[9.9e-324 4.9e-324]
 [1.5e-323 2.5e-323]
 [9.9e-324 4.9e-324]]

 [[1 2 3]
 [5 3 5]]
[[0.]
 [0.]]

 (2, 1)

 float64

 [[2 1 3]
 [5 2 1]]
0
1
[[2]
 [7]
 [9]]

 [[9 3 5]]

 [[2 5 3]
 [7 0 1]]




[['a' '23']
 ['b' '24']
 ['c' '25']
 ['d' '26']
 ['e' '27']
 ['f' '28']
 ['g' '29']
 ['h' '20']]
['1' '1' '0' '0' '1' '0' '1' '1']
[['i' '30']
 ['j' '33']]
['0' '1']


In [ ]:
import numpy as np

def train_test_split(data,train_percent):
  midpoint=train_percent*len(data)/100
  train,test=data[:int(midpoint),:],data[int(midpoint):,:]
  X_train,y_train=train[:,:-1],train[:, -1]
  X_test,y_test=test[:,:-1],test[:, -1]
  return X_train,y_train,X_test,y_test

data=np.array([['a',23,1],['b',24,1],['c',25,0],['d',26,0],['e',27,1],['f',28,0],['g',29,1]
       ,['h',20,1],['i',30,1],['j',33,1]])
input_train,output_train,input_test,output_test=train_test_split(data,75)

print(input_train)
print(output_train)
print('\n',input_test)
print(output_test)

data = np.array([[1,2,4],[6,2,2],[66,33,11]])
mod=data.reshape(data.shape[0],data.shape[1],1)
print('Rows: ',data.shape[0])
print('columns: ',data.shape[1])
print('\n\n\n')
print(mod)

[['a' '23']
 ['b' '24']
 ['c' '25']
 ['d' '26']
 ['e' '27']
 ['f' '28']
 ['g' '29']]
['1' '1' '0' '0' '1' '0' '1']

 [['h' '20']
 ['i' '30']
 ['j' '33']]
['1' '1' '1']
Rows:  3
columns:  3




[[[ 1]
  [ 2]
  [ 4]]

 [[ 6]
  [ 2]
  [ 2]]

 [[66]
  [33]
  [11]]]


In [ ]:
from scipy.linalg import lu
import numpy as np

A=np.array([[5,2,3]
            ,[5,2,3]
            ,[7,4,2]])

B=np.array([[3,2,1]
            ,[7,2,1]
            ,[7,3,4]])
C=np.tensordot(A,B,axes=0)
P,L,U=lu(A)
print(C)
print(P)
print(L)
print(U)


[[[[15 10  5]
   [35 10  5]
   [35 15 20]]

  [[ 6  4  2]
   [14  4  2]
   [14  6  8]]

  [[ 9  6  3]
   [21  6  3]
   [21  9 12]]]


 [[[15 10  5]
   [35 10  5]
   [35 15 20]]

  [[ 6  4  2]
   [14  4  2]
   [14  6  8]]

  [[ 9  6  3]
   [21  6  3]
   [21  9 12]]]


 [[[21 14  7]
   [49 14  7]
   [49 21 28]]

  [[12  8  4]
   [28  8  4]
   [28 12 16]]

  [[ 6  4  2]
   [14  4  2]
   [14  6  8]]]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.71428571 1.         0.        ]
 [0.71428571 1.         1.        ]]
[[ 7.          4.          2.        ]
 [ 0.         -0.85714286  1.57142857]
 [ 0.          0.          0.        ]]


In [ ]:
var1,var2,var3=3,4,6
max_var=max(var1,var2,var3)
print(max_var)

6


In [ ]:
fruits=["orange","appel","mango"]
x=fruits.remove("appel")
fruits[0]="kiwi"
print(fruits)

fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(fruits[2:5])



['kiwi', 'mango']
['cherry', 'orange', 'kiwi']


In [ ]:
fruits = {"apple", "banana", "cherry"}
x=fruits.remove("apple")
print(fruits)

{'banana', 'cherry'}


In [ ]:
car ={
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x=car.pop("model")
cl=car.clear()
print(car)

{}


In [ ]:
i=int(input())
if i < 6:
    print(i)


3
3


In [ ]:
for i in range(1,10):
    if (i == 3):
      continue
    else:
      print(i)

1
2
4
5
6
7
8
9


In [ ]:
txt="Hello World"
x=txt.replace("H","J")
print(x)

def my_function(x,y):
    return x

print(my_function("first","second"))



z=lambda x:x+5
z(3)
 

Jello World
first


8

In [ ]:
x = True
print(type(x))


<class 'bool'>


In [ ]:
def sum(x,y):
    z=x+y
    return z
z=sum(5,10)
x,y,z=z,z,z
print(x,y,z)

15 15 15


In [ ]:
txt = "             Hello World "
x=txt.strip()
print(x)

Hello World


In [ ]:
car ={
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car2=car.pop("model")
print(car)


{'brand': 'Ford', 'year': 1964}


In [ ]:
from numpy import zeros 
import numpy as np
